name: RedditSDK
options:
   miniumXcodeGenVersion: 2.14
   createIntermediateGroups: true
   generateEmptyDirectories: true
   usesTabs: false
   indentWidth: 4
   deploymentTarget:
     macOS: "12.0"
     iOS: "16.0"

settings:
  base:
    SWIFT_VERSION: 5.0
    CURRENT_PROJECT_VERSION: ${CI_PIPELINE_ID}
    MARKETING_VERSION: ${SDK_VERSION}
    PRODUCT_BUNDLE_IDENTIFIER: ${BUNDLE_ID}
    DEVELOPMENT_TEAM: ${TEAM_ID}

targets:
  RedditSDK:
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: ${SDK_NAME}
        NSHumanReadableCopyright: ${NS_HUMAM_READABLE}
    type: framework
    platform: iOS
    deploymentTarget: "16.0"
    scheme:
      testTargets:
        - RedditSDKTests
    settings:
      base:
        BUILD_LIBRARY_FOR_DISTRIBUTION: YES
    preBuildScripts:
      - path: scripts/swiftlint.sh
        name: Swiftlint
      - path: scripts/swiftformat.sh
        name: Swiftformat
    sources: Sources
    dependencies:
      - package: AppAuth
      
  RedditTestHost:
    info:
      path: TestHost/Info.plist
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: TestHost
    dependencies:
      - package: AppAuth
    
  RedditSDKTests:
    info:
      path: Tests/Info.plist
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    sources: Tests
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: ${BUNDLE_ID_TESTHOST}
    dependencies:
      - target: RedditSDK
      - target: RedditTestHost
      
packages:
  AppAuth:
    url: "https://github.com/openid/AppAuth-iOS.git"
    from: "1.6.0"
