name: RedditSDK
options:
   miniumXcodeGenVersion: 2.14
   createIntermediateGroups: true
   generateEmptyDirectories: true
   usesTabs: false
   indentWidth: 4
   deploymentTarget:
     iOS: "16.0"

settings:
  base:
    SWIFT_VERSION: 5.0
    PRODUCTION_BUNDLE_IDENTIFIER: tokko55v2.RedditSDK

targets:
  RedditSDK:
    type: framework
    platform: macOS
    sources:
      - path: Sources
    settings:
      configs:
        debug:
          CUSTOM_BUILD_SETTING: DEBUG
        release:
          CUSTOM_BUILD_SETTING: Release
    preBuildScripts:
      - path: scripts/swiftlint.sh
        name: Swiftlint
      - path: scripts/swiftformat.sh
        name: Swiftformat
    dependencies:
        - package: AppAuth

packages:
  AppAuth:
    url: "https://github.com/openid/AppAuth-iOS.git"
    from: "1.6.0"
