name: Lint and Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  lint:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: make scripts executable
        run: |
            chmod +x ./scripts/swiftlint.sh
            chmod +x ./initProject.sh
      - name: Build Project
        run: ./initProject.sh
      - name: Lint RedditSDK
        run: ./scripts/swiftlint.sh

  build:
    needs: lint
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Build RedditSDK
        run: xcodebuild -scheme RedditSDK -destination 'platform=OS X,arch=x86_64'
