name: RedditSDK

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  lint:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: make script executable
        run: chmod +x ./scripts/swiftlint.sh
      - name: lint RedditSDK
        run: ./scripts/swiftlint.sh

  build:
    needs: lint
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: build RedditSDK
        run: xcodebuild -scheme RedditSDK -destination 'platform=OS X,arch=x86_64'
